/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacistIndexRouteImport } from './routes/pharmacist.index'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as PharmacistPatientIdRouteImport } from './routes/pharmacist.patient.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistIndexRoute = PharmacistIndexRouteImport.update({
  id: '/pharmacist/',
  path: '/pharmacist/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistPatientIdRoute = PharmacistPatientIdRouteImport.update({
  id: '/pharmacist/patient/$id',
  path: '/pharmacist/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patient/$id': typeof PatientIdRoute
  '/pharmacist/': typeof PharmacistIndexRoute
  '/pharmacist/patient/$id': typeof PharmacistPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient/$id': typeof PatientIdRoute
  '/pharmacist': typeof PharmacistIndexRoute
  '/pharmacist/patient/$id': typeof PharmacistPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patient/$id': typeof PatientIdRoute
  '/pharmacist/': typeof PharmacistIndexRoute
  '/pharmacist/patient/$id': typeof PharmacistPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patient/$id' | '/pharmacist/' | '/pharmacist/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patient/$id' | '/pharmacist' | '/pharmacist/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/patient/$id'
    | '/pharmacist/'
    | '/pharmacist/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientIdRoute: typeof PatientIdRoute
  PharmacistIndexRoute: typeof PharmacistIndexRoute
  PharmacistPatientIdRoute: typeof PharmacistPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/': {
      id: '/pharmacist/'
      path: '/pharmacist'
      fullPath: '/pharmacist/'
      preLoaderRoute: typeof PharmacistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/patient/$id': {
      id: '/pharmacist/patient/$id'
      path: '/pharmacist/patient/$id'
      fullPath: '/pharmacist/patient/$id'
      preLoaderRoute: typeof PharmacistPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientIdRoute: PatientIdRoute,
  PharmacistIndexRoute: PharmacistIndexRoute,
  PharmacistPatientIdRoute: PharmacistPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
